#!/bin/bash
source ~/.bashrc


### First get rid of all .pyc files.  Sometimes when debugging these
### hang around because python is using them and then pdb runs
### outdated code the next time around.

## Find out where this script resides
## (http://forums.macosxhints.com/archive/index.php/t-73839.html)

## Linux
LSOF=$(lsof -p $$ | grep -E "/"$(basename $0)"$")
MY_PATH=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
if [ $? -ne 0 ]; then
    ## OSX
    MY_PATH=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi
MY_ROOT=$(dirname $MY_PATH)

rm `find "$MY_ROOT"/.. -name '*.pyc'`
rm -rf "$MY_ROOT"/../build "$MY_ROOT"/../dist "$MY_ROOT"/../pip.egg-info

rmvirtualenv clean
mkvirtualenv --no-site-packages --unzip-setuptools clean
workon clean
easy_install -f /tmp virtualenv
easy_install -f /tmp nose
# easy_install -f /tmp scripttest

args=$*
if [ -z "$1" ]; then
    args="--failed ."
fi

nosetests -s -v --with-id $args
